services:
  backend:
    image: ${IMAGE_FULL_URL}
    container_name: ${DOCKERHUB_IMAGE_NAME}
    restart: always
    networks:
      - devfit-net
    environment:
      - TZ=Asia/Seoul
    env_file:
      - .env
  redis:
    image: "redis:alpine"
    container_name: redis
    networks:
      - devfit-net
    environment:
      - TZ=Asia/Seoul
  nginx:
    image: "nginx:alpine"
    container_name: nginx
    networks:
      - devfit-net
    environment:
      - TZ=Asia/Seoul
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

networks:
  devfit-net:
    external: true
    name: devfit-net
