services:
  backend:
    image: ${IMAGE_FULL_URL}
    container_name: ${DOCKERHUB_IMAGE_NAME}
    restart: always
    network_mode: host
    environment:
      - TZ=Asia/Seoul
    env_file:
      - .env
  redis:
    image: "redis:alpine"
    container_name: redis
    ports:
      - "6379:6379"
    network_mode: host
    environment:
      - TZ=Asia/Seoul
  nginx:
    image: "nginx:alpine"
    container_name: nginx
    network_mode: host
    environment:
      - TZ=Asia/Seoul
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
