spring:
  config:
    activate:
      on-profile: "s3"
cloud:
  aws:
    region: ${AWS_REGION}
    accessKey: ${AWS_ACCESS_KEY}
    secretKey: ${AWS_SECRET_KEY}
    bucket: ${AWS_BUCKET}
    endpoint: ${AWS_ENDPOINT}
