oauth:
  kakao:
    client-id: ${KAKAO_CLIENT_ID}
    client-secret: ${KAKAO_CLIENT_SECRET}
    redirect-uri: ${KAKAO_REDIRECT_URI}
    grant-type: ${KAKAO_CLIENT_GRANT_TYPE}
  google:
    client-id: ${GOOGLE_CLIENT_ID}
    client-secret: ${GOOGLE_CLIENT_SECRET}
    redirect-uri: ${GOOGLE_REDIRECT_URI}
    grant-type: ${GOOGLE_CLIENT_GRANT_TYPE}

jwt:
  access-token-secret: ${JWT_ACCESS_TOKEN_SECRET}
  refresh-token-secret: ${JWT_REFRESH_TOKEN_SECRET}
  access-token-expiration-time: ${JWT_ACCESS_TOKEN_EXPIRATION_TIME}
  refresh-token-expiration-time: ${JWT_REFRESH_TOKEN_EXPIRATION_TIME}
  issuer: ${JWT_ISSUER}
